parameters:
#    ac_inst3_grid.example.class: AltCloud\Instance3GridBundle\Example

services:
#    ac_inst3_grid.example:
#        class: %ac_inst3_grid.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
